### ISSUE TITLE
作者你好，我在尝试重新运行您的代码时候，因为我下载不到tf1.10版本，需要1.13

### ISSUE THREAD

**Issue by zcuuu** [LIAGM/LFattNet#2]

**Comment by zcuuu** [comment]
但是一直报错，在my_generator = myGenerator(traindata_all, traindata_label, input_size, label_size, batch_size,
                               AngualrViews, boolmask_img4, boolmask_img6, boolmask_img15)这里报错，
   
Traceback (most recent call last):
  File "/Applications/PyCharm CE 2.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE 2.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/admin/PycharmProjects/LFattNet-master/LFattNet_train.py", line 265, in <module>
    initial_epoch=iter00, verbose=1, workers=workers_num)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 115, in model_iteration
    shuffle=shuffle)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 377, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])
AttributeError: 'threadsafe_iter' object has no attribute 'shape'

**Comment by LIAGM** [comment]
Hi

For the first issue, I think installing TF 1.10 may not be a problem.
You can simply type "pip install tensorflow-gpu==1.10.0" to install TF 1.10.

For the second issue, I did not test my code on TF 1.13.
So I can not solve this problem for you.

Thanks
